# Generated by Django 4.1.2 on 2022-11-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_alter_memory_image_alter_memory_video_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=1, upload_to='images/%User/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
