# Generated by Django 4.1.2 on 2022-11-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0006_remove_interests_tags_interests_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interests',
            old_name='tags',
            new_name='tag',
        ),
    ]
