# Generated by Django 4.1.2 on 2022-11-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0007_rename_tags_interests_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'ordering': ('-create',)},
        ),
        migrations.AlterField(
            model_name='interests',
            name='tag',
            field=models.ManyToManyField(blank=True, to='memories.tags'),
        ),
    ]
