# Generated by Django 4.1.2 on 2022-11-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0011_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.CharField(choices=[('li', 'like'), ('un', 'unlike')], default='un', max_length=2),
        ),
    ]
