# Generated by Django 4.1.2 on 2022-11-15 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0016_alter_like_liker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='memory',
        ),
        migrations.AddField(
            model_name='memory',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memories.like'),
        ),
    ]
