# Generated by Django 4.1.2 on 2022-11-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0017_remove_like_memory_memory_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='like',
        ),
        migrations.AddField(
            model_name='memory',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, to='memories.like'),
        ),
    ]
