# Generated by Django 4.1.2 on 2022-11-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0019_rename_like_memory_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='liked',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
